<a href="https://colab.research.google.com/github/alishermutalov/pandas-lessons/blob/pandas-learning/WebFayllarBilanIshlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
tashkent = pd.read_html("https://en.wikipedia.org/wiki/Tashkent")

In [3]:
len(tashkent)

18

In [13]:
df = tashkent[10]
df.columns = ["Nr", 	"District", 	"Population", "Area","Density",	"Map"]
df

    Nr       District  Population   Area  Density  Map
0    1       Bektemir       31400  17.83     1761  NaN
1    2      Chilanzar      260700  29.94     8707  NaN
2    3      Yashnobod      258800  33.70     7680  NaN
3    4        Mirobod      142800  17.10     8351  NaN
4    5  Mirzo Ulugbek      285000  35.15     8108  NaN
5    6        Sergeli      105700  37.36     2829  NaN
6    7   Shayxontoxur      348300  29.70    11727  NaN
7    8        Olmazor      377100  34.50    10930  NaN
8    9        Uchtepa      278200  24.00    11592  NaN
9   10     Yakkasaray      121600  14.60     8329  NaN
10  11      Yunusabad      352000  40.60     8670  NaN
11  12     Yangihayot      132800  44.20     3005  NaN

In [15]:
import requests
r = requests.get("https://openlibrary.org/subjects/python.json?published_in=2015-2021")
df_json = pd.DataFrame(r.json()['works'])

In [16]:
df_json

,key,title,edition_count,cover_id,cover_edition_key,subject,ia_collection,lendinglibrary,printdisabled,lending_edition,lending_identifier,authors,first_publish_year,ia,public_scan,has_fulltext,availability
0,/works/OL2784125W,Learning Python,21,1312568.0,OL9497269M,"[Python (Langage de programmation), Python (li...","[americana, inlibrary, internetarchivebooks, p...",False,True,OL37873566M,einfuhrunginpyth0000lutz,"[{'key': '/authors/OL411267A', 'name': 'Mark L...",1999,einfuhrunginpyth0000lutz,False,True,"{'status': 'borrow_available', 'available_to_b..."
1,/works/OL16976951W,Think Python,11,7363360.0,OL25763659M,"[Computer programming, Software architecture, ...","[additional_collections, folkscanomy, folkscan...",False,True,OL26455778M,2015ThinkPython,"[{'key': '/authors/OL6815485A', 'name': 'Allen...",2009,2015ThinkPython,True,True,"{'status': 'open', 'available_to_browse': Fals..."
2,/works/OL17795703W,Python for bioinformatics,10,8078288.0,OL26385029M,"[Bioinformatics, Python (computer program lang...",[],False,False,,,"[{'key': '/authors/OL3871440A', 'name': 'Sebas...",2009,None,False,False,NaN
3,/works/OL21349037W,Introduction to Python for Science and Enginee...,10,NaN,None,"[Python (computer program language), Engineeri...",[],False,False,,,"[{'key': '/authors/OL4194836A', 'name': 'David...",2018,None,False,False,NaN
4,/works/OL15664278W,Head First Python,9,6681113.0,OL24596470M,"[Programming languages (electronic computers),...","[inlibrary, internetarchivebooks, popularchine...",False,True,OL35343633M,headfirstpythonz0000paul,"[{'key': '/authors/OL6867889A', 'name': 'Paul ...",2010,headfirstpythonz0000paul,False,True,"{'status': 'borrow_available', 'available_to_b..."
5,/works/OL15667639W,Mining the Social Web,9,9721114.0,OL24598391M,"[Social networking, Online social networks, Ar...","[inlibrary, internetarchivebooks, printdisabled]",False,True,OL26838560M,miningsocialwebd0000russ,"[{'key': '/authors/OL6887918A', 'name': 'Matth...",2011,miningsocialwebd0000russ,False,True,"{'status': 'borrow_available', 'available_to_b..."
6,/works/OL17422847W,Python For Data Analysis,8,7548132.0,None,"[Programming languages (Electronic computers),...",[],False,False,,,"[{'key': '/authors/OL7309633A', 'name': 'Wes M...",2012,pythonfordataana00mcki,False,False,"{'status': 'error', 'error_message': 'not foun..."
7,/works/OL6045694W,Python in a Nutshell,8,389166.0,OL7581267M,"[Python (Computer program language), Python (p...","[americanuniversity-ol, drakeuniversity-ol, in...",False,True,OL26836451M,pythoninnutshell0000mart_a1w4,"[{'key': '/authors/OL1521655A', 'name': 'Alex ...",2002,pythoninnutshell0000mart_a1w4,False,True,"{'status': 'borrow_available', 'available_to_b..."
8,/works/OL23330617W,Making music with computers,7,NaN,None,"[Computer composition, Python (Computer progra...",[],False,False,,,"[{'key': '/authors/OL3853673A', 'name': 'Bill ...",2013,None,False,False,NaN
9,/works/OL21703042W,Tour of Data Science,6,NaN,None,"[Data mining, R (Computer program language), P...",[],False,False,,,"[{'key': '/authors/OL8302653A', 'name': 'Nailo...",2020,None,False,False,NaN
10,/works/OL19548251W,Python for Everyone,6,8514962.0,OL26838816M,"[Python (computer program language), Python (C...",[],False,False,,,"[{'key': '/authors/OL6972451A', 'name': 'Cay S...",2013,None,False,False,NaN
11,/works/OL14940051W,Natural Language Processing With Python,6,6296394.0,OL23978297M,"[Python (Computer program language), Natural l...",[],False,False,,,"[{'key': '/authors/OL6770736A', 'name': 'Edwar...",2009,naturallanguagep00bird_504,False,False,"{'status': 'error', 'error_message': 'not foun..."

In [18]:
!wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip

--2024-12-08 12:49:42--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 172.67.172.250, 104.21.30.141, 2606:4700:3037::ac43:acfa, ...
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|172.67.172.250|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip’

chinook.zip         100%[===================>] 298.43K  --.-KB/s    in 0.03s

2024-12-08 12:49:42 (8.81 MB/s) - ‘chinook.zip’ saved [305596/305596]

In [19]:
!unzip chinook.zip

Archive:  chinook.zip
  inflating: chinook.db

In [20]:
import sqlite3 as sql
from pprint import pprint as print

In [22]:
db = sql.connect("chinook.db")
cursor = db.cursor()

In [23]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
cursor.fetchall()

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [26]:
cursor.execute("SELECT COUNT (*) FROM employees")
cursor.fetchone()

(8,)

In [27]:
cursor.execute("PRAGMA table_info(customers)")
cursor.fetchall()

[(0, 'CustomerId', 'INTEGER', 1, None, 1),
 (1, 'FirstName', 'NVARCHAR(40)', 1, None, 0),
 (2, 'LastName', 'NVARCHAR(20)', 1, None, 0),
 (3, 'Company', 'NVARCHAR(80)', 0, None, 0),
 (4, 'Address', 'NVARCHAR(70)', 0, None, 0),
 (5, 'City', 'NVARCHAR(40)', 0, None, 0),
 (6, 'State', 'NVARCHAR(40)', 0, None, 0),
 (7, 'Country', 'NVARCHAR(40)', 0, None, 0),
 (8, 'PostalCode', 'NVARCHAR(10)', 0, None, 0),
 (9, 'Phone', 'NVARCHAR(24)', 0, None, 0),
 (10, 'Fax', 'NVARCHAR(24)', 0, None, 0),
 (11, 'Email', 'NVARCHAR(60)', 1, None, 0),
 (12, 'SupportRepId', 'INTEGER', 0, None, 0)]

In [29]:
cursor.execute("SELECT * FROM customers")
customers = cursor.fetchall()

In [38]:
df = pd.read_sql("SELECT CustomerId, FirstName, LastName FROM customers", db, index_col='CustomerId')
df

            FirstName      LastName
CustomerId
1                Luís     Gonçalves
2              Leonie        Köhler
3            François      Tremblay
4               Bjørn        Hansen
5           František   Wichterlová
6              Helena          Holý
7              Astrid        Gruber
8                Daan       Peeters
9                Kara       Nielsen
10            Eduardo       Martins
11          Alexandre         Rocha
12            Roberto       Almeida
13           Fernanda         Ramos
14               Mark       Philips
15           Jennifer      Peterson
16              Frank        Harris
17               Jack         Smith
18           Michelle        Brooks
19                Tim         Goyer
20                Dan        Miller
21              Kathy         Chase
22            Heather       Leacock
23               John        Gordon
24              Frank       Ralston
25             Victor       Stevens
26            Richard    Cunningham
27            Patrick          Gray
28              Julia       Barnett
29             Robert         Brown
30             Edward       Francis
31             Martha          Silk
32              Aaron      Mitchell
33              Ellie      Sullivan
34               João     Fernandes
35           Madalena       Sampaio
36             Hannah     Schneider
37               Fynn    Zimmermann
38             Niklas      Schröder
39            Camille       Bernard
40          Dominique      Lefebvre
41               Marc        Dubois
42              Wyatt        Girard
43           Isabelle       Mercier
44              Terhi    Hämäläinen
45           Ladislav        Kovács
46               Hugh      O'Reilly
47              Lucas       Mancini
48           Johannes  Van der Berg
49          Stanisław        Wójcik
50            Enrique         Muñoz
51             Joakim     Johansson
52               Emma         Jones
53               Phil        Hughes
54              Steve        Murray
55               Mark        Taylor
56              Diego     Gutiérrez
57               Luis         Rojas
58              Manoj        Pareek
59               Puja    Srivastava